name: cicd_pipeline_snowflake
 
on:
  push:
    branches:
      - main
    paths:
      - 'dbscripts/**'
 
  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:
    # inputs:
    #   environment:
    #     type: choice
    #     description: 'Select environment'
    #     required: true
    #     default: 'DEV'
    #     options:
    #       - DEV
    #       - TST
    #       - PRD
 
 
jobs:
  cicd_pipeline_snowflake:
    runs-on: ubuntu-latest
 
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so our job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SNOWFLAKE_CONNECTIONS_ACCOUNT: ${{ secrets.SNOWFLAKE_CONNECTIONS_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_USER: ${{ secrets.SNOWFLAKE_CONNECTIONS_USER }}
          SNOWFLAKE_CONNECTION_PASSWORD: ${{ secrets.SNOWFLAKE_CONNECTION_PASSWORD }}
          SNOWFLAKE_CONNECTIONS_ROLES: ${{ secrets.SNOWFLAKE_CONNECTIONS_ROLES }}
          SNOWFLAKE_CONNECTION_WAREHOUSE: ${{ secrets.SNOWFLAKE_CONNECTION_WAREHOUSE }}
          SNOWFLAKE_CONNECTIONS_DATABASE: ${{ secrets.SNOWFLAKE_CONNECTIONS_DATABASE }}
          SNOWFLAKE_CONNECTIONS_SCHEMA: ${{ secrets.SNOWFLAKE_CONNECTIONS_SCHEMA }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange


          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/dbscripts -a $SNOWFLAKE_CONNECTIONS_ACCOUNT -u $SNOWFLAKE_CONNECTIONS_USER -p $SNOWFLAKE_CONNECTION_PASSWORD -r "$SNOWFLAKE_CONNECTIONS_ROLES" -w $SNOWFLAKE_CONNECTION_WAREHOUSE -d $SNOWFLAKE_CONNECTIONS_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
